import { Platform } from 'react-native';
import type { MarkdownStyle } from 'react-native-enriched-markdown';

export const customMarkdownStyle: MarkdownStyle = {
  paragraph: {
    fontFamily: 'Montserrat-Regular',
    fontSize: 16,
    color: '#1f2937',
    lineHeight: Platform.select({ ios: 24, android: 26, default: 26 }),
    marginBottom: 16,
  },
  h1: {
    fontFamily: 'Montserrat-Bold',
    fontSize: 30,
    color: '#111827',
    lineHeight: Platform.select({ ios: 36, android: 38, default: 38 }),
    marginBottom: 8,
  },
  h2: {
    fontFamily: 'Montserrat-Bold',
    fontSize: 24,
    color: '#111827',
    lineHeight: Platform.select({ ios: 30, android: 32, default: 32 }),
    marginBottom: 8,
  },
  h3: {
    fontFamily: 'Montserrat-SemiBold',
    fontSize: 20,
    color: '#1f2937',
    lineHeight: Platform.select({ ios: 26, android: 28, default: 28 }),
    marginBottom: 8,
  },
  h4: {
    fontFamily: 'Montserrat-SemiBold',
    fontSize: 18,
    color: '#1f2937',
    lineHeight: Platform.select({ ios: 24, android: 26, default: 26 }),
    marginBottom: 8,
  },
  h5: {
    fontFamily: 'Montserrat-Medium',
    fontSize: 16,
    color: '#374151',
    lineHeight: Platform.select({ ios: 22, android: 24, default: 24 }),
    marginBottom: 8,
  },
  h6: {
    fontFamily: 'Montserrat-Medium',
    fontSize: 14,
    color: '#4b5563',
    lineHeight: Platform.select({ ios: 20, android: 22, default: 22 }),
    marginBottom: 8,
  },
  blockquote: {
    fontFamily: 'Montserrat-Italic',
    fontSize: 16,
    color: '#4b5563',
    lineHeight: Platform.select({ ios: 24, android: 26, default: 26 }),
    borderColor: '#d1d5db',
    borderWidth: 3,
    backgroundColor: '#f9fafb',
    gapWidth: 16,
    marginBottom: 16,
  },
  list: {
    fontFamily: 'Montserrat-Regular',
    fontSize: 16,
    color: '#1f2937',
    lineHeight: Platform.select({ ios: 22, android: 26, default: 26 }),
    bulletColor: '#6b7280',
    bulletSize: 6,
    markerMinWidth: 20,
    markerColor: '#6b7280',
    markerFontWeight: '500',
    gapWidth: 8,
    marginLeft: 24,
    marginBottom: 16,
  },
  codeBlock: {
    fontFamily: 'CourierPrime-Regular',
    fontSize: 14,
    color: '#f3f4f6',
    backgroundColor: '#1f2937',
    borderColor: '#374151',
    borderWidth: 1,
    borderRadius: 8,
    padding: 16,
    lineHeight: Platform.select({ ios: 20, android: 22, default: 22 }),
    marginBottom: 16,
  },
  code: {
    color: '#7c3aed',
    backgroundColor: '#f5f3ff',
    borderColor: '#ddd6fe',
  },
  link: {
    fontFamily: 'Montserrat-Bold',
    color: '#2563eb',
    underline: true,
  },
  strong: {
    color: '#111827',
  },
  em: {
    color: '#4b5563',
  },
  image: {
    height: 200,
    borderRadius: 8,
    marginBottom: 16,
  },
  inlineImage: {
    size: 20,
  },
  thematicBreak: {
    color: '#e5e7eb',
    height: 1,
    marginTop: 24,
    marginBottom: 24,
  },
  table: {
    fontFamily: 'Montserrat-Regular',
    fontSize: 14,
    color: '#1f2937',
    lineHeight: Platform.select({ ios: 20, android: 22, default: 22 }),
    marginBottom: 16,
    headerFontFamily: 'Montserrat-Bold',
    headerBackgroundColor: '#f3f4f6',
    headerTextColor: '#111827',
    rowEvenBackgroundColor: '#ffffff',
    rowOddBackgroundColor: '#f9fafb',
    borderColor: '#e5e7eb',
    borderRadius: 8,
    cellPaddingHorizontal: 12,
    cellPaddingVertical: 8,
  },
  taskList: {
    checkedColor: '#2563eb',
    borderColor: '#9ca3af',
    checkboxSize: 18,
    checkboxBorderRadius: 4,
    checkmarkColor: '#ffffff',
    checkedTextColor: '#9ca3af',
    checkedStrikethrough: true,
  },
};
