import { Link, Stack, useLocalSearchParams } from 'expo-router';
import { useSQLiteContext } from 'expo-sqlite';
import { useEffect, useState } from 'react';
import MaterialIcons from '@expo/vector-icons/MaterialIcons';
import { FlatList, Pressable, View } from 'react-native';
import { ActivityIndicator, Card, Text } from 'react-native-paper';
import { CenteredEmptyState } from '@/components/screen-layout';
import { createLearningContentRepository } from '@/features/learning/data/learning-content-repository';
import { isListItemUnlocked } from '@/features/learning/learning-access-policy';
import { trackPremiumEvent } from '@/features/learning/learning-analytics';
import { getLearningNavigationAccessibility } from '@/features/learning/learning-navigation-accessibility';
import type { Faq, FaqTopic } from '@/features/learning/data/learning-types';
import { useSubscription } from '@/features/purchases/use-subscription';

export function FaqTopicsScreen() { const db = useSQLiteContext(); const [items, setItems] = useState<FaqTopic[] | null>(null); useEffect(() => { void createLearningContentRepository(db).getFaqTopics().then(setItems); }, [db]); if (!items) return <CenteredEmptyState><ActivityIndicator accessibilityLabel="Loading FAQ topics" /></CenteredEmptyState>; return <FlatList testID="faq-topics-ready" contentInsetAdjustmentBehavior="automatic" contentContainerStyle={{ gap: 10, padding: 16, paddingBottom: 32 }} ListHeaderComponent={<View style={{ gap: 6, paddingBottom: 8 }}><Text variant="labelLarge" style={{ letterSpacing: 0.8 }}>OFFLINE REFERENCE</Text><Text variant="headlineSmall">Answers when you need them.</Text><Text selectable variant="bodyMedium">Browse practical React Native guidance, saved on your device.</Text></View>} data={items} keyExtractor={(x) => String(x.faqTopicId)} renderItem={({ item, index }) => <Link href={{ pathname: '/faq/[topicId]', params: { topicId: item.faqTopicId } }} asChild><Pressable testID={`faq-topic-${index}`} accessibilityRole="button" accessibilityLabel={getLearningNavigationAccessibility({ title: item.title, destination: 'FAQ questions' })} accessibilityHint="Opens FAQ questions" style={{ minHeight: 44 }}><Card mode="outlined" style={{ borderCurve: 'continuous' }}><Card.Content style={{ alignItems: 'center', flexDirection: 'row', gap: 12, paddingVertical: 14 }}><View style={{ alignItems: 'center', backgroundColor: '#EEF4FF', borderRadius: 20, height: 40, justifyContent: 'center', width: 40 }}><MaterialIcons accessible={false} color="#005AC1" name="help-outline" size={22} /></View><Text style={{ flex: 1 }} variant="titleMedium">{item.title}</Text><MaterialIcons accessible={false} color="#56657A" name="chevron-right" size={25} /></Card.Content></Card></Pressable></Link>} />; }
export function FaqListScreen() { const { topicId } = useLocalSearchParams<{ topicId: string }>(); const db = useSQLiteContext(); const [items, setItems] = useState<Faq[] | null>(null); const { isSubscribed } = useSubscription(); useEffect(() => { void createLearningContentRepository(db).getFaqsForTopic(Number(topicId)).then(setItems); }, [db, topicId]); if (!items) return <CenteredEmptyState><ActivityIndicator accessibilityLabel="Loading FAQ answers" /></CenteredEmptyState>; return <><Stack.Screen options={{ title: 'FAQ' }} /><FlatList testID="faq-list-ready" contentInsetAdjustmentBehavior="automatic" contentContainerStyle={{ gap: 10, padding: 16, paddingBottom: 32 }} ListHeaderComponent={<View style={{ gap: 4, paddingBottom: 8 }}><Text variant="labelLarge" style={{ letterSpacing: 0.8 }}>FAQ</Text><Text selectable variant="bodyMedium">The first ten answers are available to read. Locked questions preserve the original upgrade journey.</Text></View>} data={items} keyExtractor={(x) => String(x.faqId)} renderItem={({ item, index }) => { const unlocked = isListItemUnlocked(index, isSubscribed); return <Link href={unlocked ? { pathname: '/faq/read/[faqId]', params: { faqId: item.faqId } } : '/subscription'} asChild><Pressable testID={`faq-item-${index}`} accessibilityRole="button" accessibilityLabel={getLearningNavigationAccessibility({ title: item.question, destination: 'FAQ answer', locked: !unlocked })} accessibilityHint={unlocked ? 'Opens FAQ answer' : 'Opens subscription options'} onPress={unlocked ? undefined : () => trackPremiumEvent('premium_faq_list')} style={{ minHeight: 44 }}><Card mode="outlined" style={{ borderCurve: 'continuous', opacity: unlocked ? 1 : 0.82 }}><Card.Content style={{ alignItems: 'center', flexDirection: 'row', gap: 12, paddingVertical: 13 }}><View style={{ alignItems: 'center', backgroundColor: unlocked ? '#EEF4FF' : '#F2F0F4', borderRadius: 18, height: 36, justifyContent: 'center', width: 36 }}><MaterialIcons accessible={false} color={unlocked ? '#005AC1' : '#56657A'} name={unlocked ? 'question-answer' : 'lock-outline'} size={19} /></View><View style={{ flex: 1, gap: 4 }}><Text numberOfLines={unlocked ? 3 : 1} variant="titleMedium">{item.question}</Text><Text variant="labelSmall">{unlocked ? 'Available offline' : 'Locked'}</Text></View><MaterialIcons accessible={false} color="#56657A" name={unlocked ? 'chevron-right' : 'lock-outline'} size={24} /></Card.Content></Card></Pressable></Link>; }} /></>; }
