import { Link, Stack, useLocalSearchParams } from 'expo-router';
import { useSQLiteContext } from 'expo-sqlite';
import { useEffect, useState } from 'react';
import MaterialIcons from '@expo/vector-icons/MaterialIcons';
import { FlatList, Pressable, useWindowDimensions, View } from 'react-native';
import { ActivityIndicator, Card, Text } from 'react-native-paper';
import { WebView } from 'react-native-webview';
import { CenteredEmptyState } from '@/components/screen-layout';
import { createLearningContentRepository } from '@/features/learning/data/learning-content-repository';
import { getLearningNavigationAccessibility } from '@/features/learning/learning-navigation-accessibility';
import { buildLessonReaderHtml, getLearningReaderFontSize } from '@/features/learning/learning-lesson-reader-utils';
import type { LearningCategory, LearningLibraryTool } from '@/features/learning/data/learning-types';

function Loading() { return <CenteredEmptyState><ActivityIndicator /></CenteredEmptyState>; }
export function GoodToKnowCategoriesScreen() { const db = useSQLiteContext(); const [items, setItems] = useState<LearningCategory[] | null>(null); useEffect(() => { void createLearningContentRepository(db).getCategories().then(setItems); }, [db]); if (!items) return <Loading />; return <FlatList testID="good-to-know-categories-ready" contentInsetAdjustmentBehavior="automatic" contentContainerStyle={{ gap: 10, padding: 16, paddingBottom: 32 }} ListHeaderComponent={<View style={{ gap: 6, paddingBottom: 8 }}><Text variant="labelLarge" style={{ letterSpacing: 0.8 }}>YOUR TOOLKIT</Text><Text variant="headlineSmall">Useful things to keep close.</Text><Text selectable variant="bodyMedium">Libraries, tools, and ecosystem context for day-to-day React Native work.</Text></View>} data={items} keyExtractor={(x) => String(x.categoryId)} renderItem={({ item, index }) => <Link href={{ pathname: '/good-to-know/[categoryId]', params: { categoryId: item.categoryId } }} asChild><Pressable testID={`good-to-know-category-${index}`} accessibilityRole="button" accessibilityLabel={getLearningNavigationAccessibility({ title: item.name, destination: 'Good to know resources' })} accessibilityHint="Opens Good to know resources" style={{ minHeight: 44 }}><Card mode="outlined" style={{ borderCurve: 'continuous' }}><Card.Content style={{ alignItems: 'center', flexDirection: 'row', gap: 12, paddingVertical: 14 }}><View style={{ alignItems: 'center', backgroundColor: '#EEF4FF', borderRadius: 20, height: 40, justifyContent: 'center', width: 40 }}><MaterialIcons accessible={false} color="#005AC1" name="tips-and-updates" size={22} /></View><Text style={{ flex: 1 }} variant="titleMedium">{item.name}</Text><MaterialIcons accessible={false} color="#56657A" name="chevron-right" size={25} /></Card.Content></Card></Pressable></Link>} />; }
export function GoodToKnowListScreen() { const { categoryId } = useLocalSearchParams<{ categoryId: string }>(); const db = useSQLiteContext(); const [items, setItems] = useState<LearningLibraryTool[] | null>(null); useEffect(() => { void createLearningContentRepository(db).getLibraryToolsForCategory(Number(categoryId)).then(setItems); }, [db, categoryId]); if (!items) return <Loading />; return <><Stack.Screen options={{ title: 'Good to know' }} /><FlatList testID="good-to-know-list-ready" contentInsetAdjustmentBehavior="automatic" contentContainerStyle={{ gap: 10, padding: 16, paddingBottom: 32 }} ListHeaderComponent={<View style={{ gap: 4, paddingBottom: 8 }}><Text variant="labelLarge" style={{ letterSpacing: 0.8 }}>GOOD TO KNOW</Text><Text selectable variant="bodyMedium">A practical, offline reference for the tools around React Native.</Text></View>} data={items} keyExtractor={(x) => String(x.libraryToolId)} renderItem={({ item, index }) => <Link href={{ pathname: '/good-to-know/read/[itemId]', params: { itemId: item.libraryToolId } }} asChild><Pressable testID={`good-to-know-item-${index}`} accessibilityRole="button" accessibilityLabel={getLearningNavigationAccessibility({ title: item.name, destination: 'Good to know resource' })} accessibilityHint="Opens Good to know resource" style={{ minHeight: 44 }}><Card mode="outlined" style={{ borderCurve: 'continuous' }}><Card.Content style={{ alignItems: 'center', flexDirection: 'row', gap: 12, paddingVertical: 13 }}><View style={{ alignItems: 'center', backgroundColor: '#EEF4FF', borderRadius: 18, height: 36, justifyContent: 'center', width: 36 }}><MaterialIcons accessible={false} color="#005AC1" name="extension" size={19} /></View><Text style={{ flex: 1 }} variant="titleMedium">{item.name}</Text><MaterialIcons accessible={false} color="#56657A" name="chevron-right" size={24} /></Card.Content></Card></Pressable></Link>} /></>; }
export function GoodToKnowReaderScreen() { const { itemId } = useLocalSearchParams<{ itemId: string }>(); const db = useSQLiteContext(); const [item, setItem] = useState<LearningLibraryTool | null | undefined>(); const { fontScale } = useWindowDimensions(); useEffect(() => { void createLearningContentRepository(db).getLibraryTool(Number(itemId)).then(setItem).catch(() => setItem(null)); }, [db, itemId]); if (item === undefined) return <Loading />; if (!item) return <CenteredEmptyState><Text>This item is unavailable.</Text></CenteredEmptyState>; return <View testID="good-to-know-reader-ready" style={{ flex: 1 }}><Stack.Screen options={{ title: item.name }} /><WebView originWhitelist={['*']} source={{ html: buildLessonReaderHtml(`<h2>${item.name}</h2>${item.explanation}`, getLearningReaderFontSize(fontScale)) }} /></View>; }
