import { Link, Stack, useLocalSearchParams } from 'expo-router';
import { useSQLiteContext } from 'expo-sqlite';
import { useEffect, useState } from 'react';
import MaterialIcons from '@expo/vector-icons/MaterialIcons';
import { FlatList, Pressable, useWindowDimensions, View } from 'react-native';
import { ActivityIndicator, Card, Text } from 'react-native-paper';
import { WebView } from 'react-native-webview';
import { CenteredEmptyState } from '@/components/screen-layout';
import { createLearningContentRepository } from '@/features/learning/data/learning-content-repository';
import { isListItemUnlocked } from '@/features/learning/learning-access-policy';
import { trackPremiumEvent } from '@/features/learning/learning-analytics';
import { getLearningNavigationAccessibility } from '@/features/learning/learning-navigation-accessibility';
import { buildLessonReaderHtml, getLearningReaderFontSize } from '@/features/learning/learning-lesson-reader-utils';
import type { InterviewLevelCount, InterviewQuestion } from '@/features/learning/data/learning-types';
import { useSubscription } from '@/features/purchases/use-subscription';
const names = { 1: 'Beginner', 2: 'Intermediate', 3: 'Advanced' } as const;
function Loading() { return <CenteredEmptyState><ActivityIndicator /></CenteredEmptyState>; }
export function InterviewPrepScreen() { const db = useSQLiteContext(); const [items, setItems] = useState<InterviewLevelCount[] | null>(null); useEffect(() => { void createLearningContentRepository(db).getInterviewLevelCounts().then(setItems); }, [db]); if (!items) return <Loading />; return <FlatList testID="interview-prep-ready" contentInsetAdjustmentBehavior="automatic" contentContainerStyle={{ gap: 12, padding: 16, paddingBottom: 32 }} ListHeaderComponent={<View style={{ gap: 6, paddingBottom: 8 }}><Text variant="labelLarge" style={{ letterSpacing: 0.8 }}>INTERVIEW PREP</Text><Text variant="headlineSmall">Practice with intent.</Text><Text selectable variant="bodyMedium">Choose a level and work through focused React Native questions at your own pace.</Text></View>} data={items} keyExtractor={(x) => String(x.level)} renderItem={({ item }) => <Link href={{ pathname: '/interview-prep/[level]', params: { level: item.level } }} asChild><Pressable testID={`interview-level-${item.level}`} accessibilityRole="button" accessibilityLabel={getLearningNavigationAccessibility({ title: `${names[item.level]}, ${item.count} questions`, destination: 'interview questions' })} accessibilityHint="Opens interview questions" style={{ minHeight: 44 }}><Card mode="outlined" style={{ borderCurve: 'continuous' }}><Card.Content style={{ alignItems: 'center', flexDirection: 'row', gap: 12, paddingVertical: 16 }}><View style={{ alignItems: 'center', backgroundColor: '#EEF4FF', borderRadius: 22, height: 44, justifyContent: 'center', width: 44 }}><MaterialIcons accessible={false} color="#005AC1" name="school" size={23} /></View><View style={{ flex: 1, gap: 2 }}><Text variant="titleLarge">{names[item.level]}</Text><Text selectable variant="bodyMedium">{item.count} questions</Text></View><MaterialIcons accessible={false} color="#56657A" name="chevron-right" size={26} /></Card.Content></Card></Pressable></Link>} />; }
export function InterviewListScreen() { const { level } = useLocalSearchParams<{ level: string }>(); const parsed = Number(level) as 1 | 2 | 3; const db = useSQLiteContext(); const [items, setItems] = useState<InterviewQuestion[] | null>(null); const { isSubscribed } = useSubscription(); useEffect(() => { void createLearningContentRepository(db).getInterviewQuestions(parsed).then(setItems); }, [db, parsed]); if (!items) return <Loading />; return <><Stack.Screen options={{ title: names[parsed] ?? 'Interview Prep' }} /><FlatList testID="interview-list-ready" contentInsetAdjustmentBehavior="automatic" contentContainerStyle={{ gap: 10, padding: 16, paddingBottom: 32 }} ListHeaderComponent={<View style={{ gap: 4, paddingBottom: 8 }}><Text variant="labelLarge" style={{ letterSpacing: 0.8 }}>{names[parsed]?.toUpperCase() ?? 'INTERVIEW PREP'}</Text><Text selectable variant="bodyMedium">The first ten questions are available to read. Locked questions retain the original upgrade journey.</Text></View>} data={items} keyExtractor={(x) => String(x.questionId)} renderItem={({ item, index }) => { const unlocked = isListItemUnlocked(index, isSubscribed); return <Link href={unlocked ? { pathname: '/interview-prep/read/[questionId]', params: { questionId: item.questionId } } : '/subscription'} asChild><Pressable testID={`interview-item-${index}`} accessibilityRole="button" accessibilityLabel={getLearningNavigationAccessibility({ title: item.question, destination: 'interview question', locked: !unlocked })} accessibilityHint={unlocked ? 'Opens interview question' : 'Opens subscription options'} onPress={unlocked ? undefined : () => trackPremiumEvent('premium_interview_questions_list')} style={{ minHeight: 44 }}><Card mode="outlined" style={{ borderCurve: 'continuous', opacity: unlocked ? 1 : 0.82 }}><Card.Content style={{ alignItems: 'center', flexDirection: 'row', gap: 12, paddingVertical: 13 }}><View style={{ alignItems: 'center', backgroundColor: unlocked ? '#EEF4FF' : '#F2F0F4', borderRadius: 18, height: 36, justifyContent: 'center', width: 36 }}><MaterialIcons accessible={false} color={unlocked ? '#005AC1' : '#56657A'} name={unlocked ? 'record-voice-over' : 'lock-outline'} size={19} /></View><View style={{ flex: 1, gap: 4 }}><Text numberOfLines={unlocked ? 3 : 1} variant="titleMedium">{item.question}</Text><Text variant="labelSmall">{unlocked ? 'Available offline' : 'Locked'}</Text></View><MaterialIcons accessible={false} color="#56657A" name={unlocked ? 'chevron-right' : 'lock-outline'} size={24} /></Card.Content></Card></Pressable></Link>; }} /></>; }
export function InterviewReaderScreen() { const { questionId } = useLocalSearchParams<{ questionId: string }>(); const db = useSQLiteContext(); const [item, setItem] = useState<InterviewQuestion | null | undefined>(); const { fontScale } = useWindowDimensions(); useEffect(() => { void createLearningContentRepository(db).getInterviewQuestion(Number(questionId)).then(setItem).catch(() => setItem(null)); }, [db, questionId]); if (item === undefined) return <Loading />; if (!item) return <CenteredEmptyState><Text>This question is unavailable.</Text></CenteredEmptyState>; return <View testID="interview-reader-ready" style={{ flex: 1 }}><Stack.Screen options={{ title: 'Interview Prep' }} /><WebView originWhitelist={['*']} source={{ html: buildLessonReaderHtml(`<h2>${item.question}</h2>${item.explanation}`, getLearningReaderFontSize(fontScale)) }} /></View>; }
