import type { Preset } from '../../types';
import { numBeats } from './constants';

const Empty: Preset = {
  name: 'Empty',
  bpm: 120,
  pattern: [
    {
      instrumentName: 'hi-hat',
      steps: new Array(numBeats).fill(false),
    },
    {
      instrumentName: 'clap',
      steps: new Array(numBeats).fill(false),
    },
    {
      instrumentName: 'kick',
      steps: new Array(numBeats).fill(false),
    },
  ],
};

const BosaNova: Preset = {
  name: 'Bosa Nova',
  bpm: 120,
  pattern: [
    {
      instrumentName: 'hi-hat',
      steps: new Array(numBeats).fill(true),
    },
    {
      instrumentName: 'clap',
      steps: [
        true,
        false,
        false,
        true,
        false,
        false,
        true,
        false,
        false,
        false,
        true,
        false,
        false,
        true,
        false,
        false,
      ],
    },
    {
      instrumentName: 'kick',
      steps: [
        true,
        false,
        false,
        true,
        true,
        false,
        false,
        true,
        true,
        false,
        false,
        true,
        true,
        false,
        false,
        true,
      ],
    },
  ],
};

const basicGroove: Preset = {
  name: 'Rock Groove 1',
  bpm: 120,
  pattern: [
    {
      instrumentName: 'hi-hat',
      steps: new Array(numBeats).fill(true),
    },
    {
      instrumentName: 'clap',
      steps: [
        false,
        false,
        true,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
        true,
        false,
      ],
    },
    {
      instrumentName: 'kick',
      steps: [
        true,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
      ],
    },
  ],
};

const basicGroove2: Preset = {
  name: 'Rock Groove 2',
  bpm: 120,
  pattern: [
    {
      instrumentName: 'hi-hat',
      steps: new Array(numBeats).fill(true),
    },
    {
      instrumentName: 'clap',
      steps: [
        false,
        false,
        true,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
        true,
        false,
      ],
    },
    {
      instrumentName: 'kick',
      steps: [
        true,
        false,
        false,
        false,
        true,
        true,
        false,
        false,
        true,
        false,
        false,
        false,
        true,
        true,
        false,
        false,
      ],
    },
  ],
};

const basicGroove3: Preset = {
  name: 'Rock Groove 3',
  bpm: 120,
  pattern: [
    {
      instrumentName: 'hi-hat',
      steps: new Array(numBeats).fill(true),
    },
    {
      instrumentName: 'clap',
      steps: [
        false,
        false,
        true,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
        true,
        false,
      ],
    },
    {
      instrumentName: 'kick',
      steps: [
        true,
        false,
        false,
        true,
        false,
        true,
        false,
        false,
        true,
        false,
        false,
        true,
        false,
        true,
        false,
        false,
      ],
    },
  ],
};

const BreakBeat1: Preset = {
  name: 'Break Beat 1',
  bpm: 240,
  pattern: [
    {
      instrumentName: 'hi-hat',
      steps: [
        true,
        false,
        true,
        false,
        true,
        false,
        true,
        false,
        true,
        false,
        true,
        false,
        true,
        false,
        true,
        false,
      ],
    },
    {
      instrumentName: 'clap',
      steps: [
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        true,
        false,
        true,
        false,
        false,
        true,
        false,
        false,
        false,
      ],
    },
    {
      instrumentName: 'kick',
      steps: [
        true,
        false,
        false,
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
        false,
        false,
      ],
    },
  ],
};

const BreakBeat2: Preset = {
  name: 'Break Beat 2',
  bpm: 188,
  pattern: [
    {
      instrumentName: 'hi-hat',
      steps: [
        true,
        false,
        true,
        false,
        true,
        false,
        true,
        false,
        true,
        false,
        true,
        false,
        true,
        false,
        true,
        false,
      ],
    },
    {
      instrumentName: 'clap',
      steps: [
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        true,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
      ],
    },
    {
      instrumentName: 'kick',
      steps: [
        true,
        false,
        true,
        true,
        false,
        false,
        false,
        false,
        true,
        false,
        true,
        false,
        false,
        false,
        false,
        false,
      ],
    },
  ],
};

const LinearGroove: Preset = {
  name: 'Linear Groove',
  bpm: 105,
  pattern: [
    {
      instrumentName: 'hi-hat',
      steps: [
        false,
        true,
        false,
        false,
        true,
        false,
        true,
        false,
        true,
        false,
        false,
        true,
        false,
        false,
        true,
        false,
      ],
    },
    {
      instrumentName: 'clap',
      steps: [
        false,
        false,
        true,
        false,
        false,
        true,
        false,
        true,
        false,
        true,
        false,
        false,
        true,
        false,
        false,
        true,
      ],
    },
    {
      instrumentName: 'kick',
      steps: [
        true,
        false,
        false,
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        true,
        false,
        false,
      ],
    },
  ],
};

const WWRYGroove: Preset = {
  name: 'WWRY',
  bpm: 81,
  pattern: [
    {
      instrumentName: 'hi-hat',
      steps: new Array(numBeats).fill(false),
    },
    {
      instrumentName: 'clap',
      steps: [
        false,
        false,
        true,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
        true,
        false,
      ],
    },
    {
      instrumentName: 'kick',
      steps: [
        true,
        true,
        false,
        false,
        true,
        true,
        false,
        false,
        true,
        true,
        false,
        false,
        true,
        true,
        false,
        false,
      ],
    },
  ],
};

const presets: Record<string, Preset> = {
  Empty,
  'Bosa Nova': BosaNova,
  'Rock Groove 1': basicGroove,
  'Rock Groove 2': basicGroove2,
  'Rock Groove 3': basicGroove3,
  'Break Beat 1': BreakBeat1,
  'Break Beat 2': BreakBeat2,
  'Linear Groove': LinearGroove,
  'WWRY': WWRYGroove,
};

export default presets;
